### ISSUE TITLE
Lack of 2-decimal support

### ISSUE THREAD

**Issue by vylion** [andrewsarnold/FlagMaker-Jr#2]
This tool is wonderful. One feature I missed, though, would be to allow 2 decimals in position numbers. For example, when trying to make [2 white mountains in the lower half over a St. George cross with the white field changed to yellow](https://cloud.githubusercontent.com/assets/13038852/10270042/dd10b614-6ae6-11e5-925c-3347029e8931.png), the peaks had to be slightly off-centre because I can't put the X2 positions of each triangle in 0.75 and 2.25 respectively.

**Comment by andrewsarnold** [comment]
Uncheck the check box on the right side of to the "X2" slider. Then you can click the number on the left side of the slider and type whatever you want. It displays 2 decimal digits but will store however many you type.
